### ISSUE TITLE
Create .gitignore File

### ISSUE THREAD

**Issue by rahul188** [Divu03/AcmegreadProject#2]
Needs to create .gitignore file & put folder/Files inside that.

**Comment by Divu03** [comment]
.gitignore file is there in the local directory do we really need to put it here

**Comment by Divu03** [comment]
It is there in the project

**Comment by rahul188** [comment]
> It is there in the project

Please add, .idea folder also in that

**Comment by Divu03** [comment]
Can you elaborate that
